sudo: false

language: ruby
cache: bundler
rvm:
  - 2.3.3

before_install:
  - test $TRAVIS_PULL_REQUEST && ./.travis/pr_status pending "Waiting for website to build"

script:
  - bash .travis/build.sh
# before_deploy:
#   - bash .travis/pre-deploy.sh

after_success:
  - test $TRAVIS_PULL_REQUEST && ./.travis/pr_deploy
after_failure:
  - test $TRAVIS_PULL_REQUEST && ./.travis/pr_status error "Website failed to build"

# deploy:
#   provider: azure_web_apps
env:
  global:
    - GITHUB_AUTH_USER=allejo
    - GITHUB_USER=CityofSantaMonica
    - GITHUB_REPO=beta-smgov
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
